apiVersion: v1
name: terjang
version: 0.0.3
appVersion: "latest"
description: Scalable HTTP load testing tool built on Vegeta
keywords:
- load-test
- load-testing
- benchmarking
- http
home: https://github.com/andylibrian/terjang
sources:
- https://github.com/andylibrian/terjang
maintainers:
- name: Andy Librian
  email: andy.librian@gmail.com
