image:
  repository: ghcr.io/andylibrian/terjang
  tag: latest

server:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 
    memory: 

worker:
  replicas: 1
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 
    memory: 


