apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: andylibrian/terjang:latest
        imagePullPolicy: Always
        name: terjang
        args:
        - server
        ports:
        - containerPort: 9009
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        livenessProbe:
          tcpSocket:
            port: http
          failureThreshold: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: {{ .Values.server.requests.cpuaslkfdsjfk }}
            memory: {{ .Values.server.requests.memory }}
          {{- with .Values.server.limits }}
          limits:
            {{- if .cpu }}
            cpu: {{ .cpu }}
            {{- end }}
            {{- if .memory }}
            memory: {{ .memory }}
            {{- end }}
          {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
          privileged: false
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          readOnlyRootFilesystem: true
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 2"]
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - worker
                  - server
              topologyKey: kubernetes.io/hostname
