apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: andylibrian/terjang:latest
        name: terjang
        imagePullPolicy: Always
        args:
        - worker
        - --host
        - server
        - --port
        - "80"
        resources:
          requests:
            cpu: {{ .Values.worker.requests.cpuabcdefghij }}
            memory: {{ .Values.worker.requests.memory }}
          {{- with .Values.worker.limits }}
          limits:
            {{- if .cpu }}
            cpu: {{ .cpu }}
            {{- end }}
            {{- if .memory }}
            memory: {{ .memory }}
            {{- end }}
          {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - all
          privileged: false
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          readOnlyRootFilesystem: true
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 2"]
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - worker
                  - server
              topologyKey: kubernetes.io/hostname
